- name: Create the string redis client port range
  set_fact:
    port_range: "{{ redis_start_port|string }}:{{ (redis_start_port|int + redis_instance_per_machine|int - 1)|string }}"

- name: Create the string redis backend port range
  set_fact:
    back_port_range: "{{ (redis_start_port|int + 10000)|string }}:{{ (redis_start_port|int + redis_instance_per_machine|int + 9999)|string }}"

- name: Configure UFW rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('any') }}"
    interface: "{{ item.interface | default(omit) }}"
    direction: "{{ item.direction | default('in') }}"
    src: "{{ item.src | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
  with_items:
    - rule: 'allow'
      port: 'ssh'
      comment: 'Allow SSH'

    - rule: 'allow'
      port: '{{ port_range }}'
      proto: 'tcp'
      interface: "{{ main_interface }}"
      src: 'any'
      comment: 'redis client'

    - rule: 'allow'
      port: '{{ port_range }}'
      proto: 'udp'
      interface: "{{ main_interface }}"
      src: 'any'
      comment: 'redis client'

    - rule: 'allow'
      port: '{{ port_range }}'
      proto: 'tcp'
      interface: "{{ sync_interface }}"
      src: '{{ sync_interface_subnet }}'
      comment: 'redis intercommunication'

    - rule: 'allow'
      port: '{{ port_range }}'
      proto: 'udp'
      interface: "{{ sync_interface }}"
      src: '{{ sync_interface_subnet }}'
      comment: 'redis intercommunication'

    - rule: 'allow'
      port: '{{ back_port_range }}'
      proto: 'tcp'
      interface: "{{ sync_interface }}"
      src: '{{ sync_interface_subnet }}'
      comment: 'redis intercommunication'

    - rule: 'allow'
      port: '{{ back_port_range }}'
      proto: 'udp'
      interface: "{{ sync_interface }}"
      src: '{{ sync_interface_subnet }}'
      comment: 'redis intercommunication'

- name: Set UFW default policies
  ufw:
    default: "{{ item.default }}"
    direction: "{{ item.direction }}"
  with_items:
    - {default: 'deny', direction: 'incoming'}
    - {default: 'allow', direction: 'outgoing'}


- name: Enable UFW
  ufw:
    state: enabled
