- name: Stop Redis services
  systemd:
    name: "redis-server-{{ item }}"
    state: stopped
    daemon_reload: true
    enabled: true
  with_items: "{{ range(1, redis_instance_per_machine + 1) | list }}"