- name: Install required packages
  apt:
    name:
      - lsb-release
      - curl
      - gpg
    state: present

- name: Add Redis GPG key
  apt_key:
    url: https://packages.redis.io/gpg
    state: present

- name: Add Redis repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb {{ ansible_lsb.codename }} main
    state: present
    filename: redis

- name: Update apt cache
  apt:
    update_cache: true

- name: Install Redis
  apt:
    name: redis
    state: present
